"""
set of useful function to determine if different process steps
that terminated without error generated the correct output.
Ex. missing positions after parsing the data
"""

from typing import *
from prefect import task
from prefect.engine import signals
import re
import numpy as np
from pathlib import Path

from pysmFISH.logger_utils import prefect_logging_setup


@task(name='qc_matching_pkl')
def check_matching_metadata_robofish(all_raw_files:list):
    """
    This function is used to check that each of the nd2 files
    generated by the microscope has a matching pkl metadata
    file generated by robofish

    Args:
        all_raw_files: list
            list with all the paths of the nd2 files to process

    """

    logger = prefect_logging_setup('qc_config_pkl')
    experiment_fpath = all_raw_files[0].parent
    all_info_files = list(experiment_fpath.glob('*.pkl'))
  
    if len(all_info_files) == 0:
        logger.error(f"no .pkl files in the folder")
        raise signals.FAIL()

    # Determine if there are multiple metadata files with same number
    all_codes = []
    for meta_file_path in all_info_files:
        # collect the count code
        count_code = re.search(r'(Count)\d{5}', meta_file_path.stem)
        assert count_code, logger.error(f'{meta_file_path.stem} does not contain the CountXXXXX code')
        count_code = count_code.group()
        all_codes. append(count_code)
    
    if all_codes:
        all_codes_counts_dict = {i:all_codes.count(i) for i in all_codes}
        all_codes_counts_array = np.array(list(all_codes_counts_dict.values()))
        if np.any(all_codes_counts_array>1):
            for count_code,value in all_codes_counts_dict.items():
                if value >1:
                    logger.error(f' multiple pkl files with {count_code}')
                    raise signals.FAIL()
            
            logger.error(f'fix naming of the files with the repeated codes')
            raise signals.FAIL()

    missing_pkl = []
    for nd2_file_path in all_raw_files:
        # collect the count code
        try:
            count_code = re.search(r'(Count)\d{5}', nd2_file_path.stem).group()
        except:
            count_code = None
            logger.error(f'{nd2_file_path.stem} does not contain the CountXXXXX code')
        try:
            info_file = [info_file for info_file in all_info_files if count_code  in info_file.stem][0]
        except IndexError:
            logger.error(f'{nd2_file_path.stem} does not have the corresponding pkl file')
            missing_pkl.append(nd2_file_path.stem)

    if missing_pkl:
        logger.error(f'collect the missing pkl for {missing_pkl} before parsing')
        raise signals.FAIL()